apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataingestionmastodon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataingestionmastodon
  template:
    metadata:
      labels:
        app: dataingestionmastodon
    spec:
      containers:
      - name: dataingestionmastodon
        image: dataingestionmastodon:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: dataingestionmastodon
spec:
  selector:
    app: dataingestionmastodon
  ports:
  - port: 5000
    targetPort: 5000