services:
  # Discord Bot serving as main terminal for the user
  musclebot:
    build:
      context: ./ContainerMuscleBot/MuscleBot
      dockerfile: Dockerfile
    container_name: musclebot
    depends_on:
      - dataingestion
      - dataprocessing
    restart: unless-stopped
    volumes:
      - ./ContainerMuscleBot/MuscleBot/config:/app/config

  # Service to manages all interactions in regards to user profiles for our API
  userprofileservice:
    build:
      context: ./ContainerUserProfile/UserProfileService
      dockerfile: Dockerfile
    container_name: userprofileservice
    restart: unless-stopped

  # Service to manages Ingestion of feeds from a given social medial outlet
  dataingestion:
    build:
      context: ./dataingestion
      dockerfile: Dockerfile
    container_name: dataingestion
    ports:
      - "5000:5000"
    restart: unless-stopped

  # Service to processes feeds into a digestable form
  dataprocessing:
    build:
      context: ./dataprocessing
      dockerfile: Dockerfile
    container_name: dataprocessing
    restart: unless-stopped